### PR TITLE
The resource for backup a system state of a windows server.

### PR DESCRIPTION
**Pull request by Kasen**
I wrote resource/provider for backup a system state of a windows server. This can be useful for backup active directory for example.

### CODE REVIEW

**Comment by Kasen** [comment]
@legal90 @scopenco can you review this PR?

**Comment by legal90** [comment]
LGTM :+1:

**Comment by knazarov** [comment]
Please try to write commit messages a bit cleaner. Example:
- README.md changed
  could be renamed to
- README.md: add windows system state backup

**Comment by knazarov** [comment]
LGTM :+1:

**Pull request merged**
